name: Uda-Crafts-flow
# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branches:
      - master
  schedule:
       # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * 0'
# Use a matrix strategy to use Node.js versions 16.x and 18.x
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]	

    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure the repository is checked out

      # Set up a Node.js environment using the specified node version.
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  # Ensure compatibility with Node.js version 20

      # Install the dependencies.
      - name: Install dependencies for custom action
        run: cd backend && npm ci

      # Run the tests.
      - name: Run tests
        run: cd   backend && npm test

      # Run the linter.
      - run: cd backend && npm run lint

      # Send a console message at completion.	  
      - run: |
          echo "Hello ${GITHUB_ACTOR}. You pushed to ${GITHUB_REPOSITORY} at $(date)."

